source 'https://github.com/CocoaPods/Specs.git'
target 'app_qr' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket'
  ]
  pod 'react-native-braintree', :path => '../node_modules/react-native-braintree'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
end